name: Run tests

on:
  - workflow_dispatch
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version:
          - 2.7
          - 3.5
          - 3.6
          - 3.7
          - 3.8
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install shells on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt install zsh
      - name: Install shells on macOS
        if: runner.os == 'macOS'
        run: |
          brew install zsh
      - name: Install tox
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install tox
      - name: Run tox
        run: |
          python -m tox -e test-ci
